### ISSUE TITLE
Typos in the book

### ISSUE THREAD

**Issue by miklossy** [LorenzoBettini/tdd-buildautomation-ci-book-examples#1]

**Comment by miklossy** [comment]
- on page 3: `e2d tests` should be `e2e tests`
- on page 6: `the the` should be `the `
- on page 20: `The Quick Access is a also` should be `The Quick Access is also a`
- on page 21: `save it in the very project` should be `save it in the project`
- on page 23: `i the “Open Type” dialog` should be `in the “Open Type” dialog`
- on page 50: `has an hard-coded dependency` should be `has a hard-coded dependency`
- on page 53: `these constants ... make it private` should be `these constants ... make them private`
- on page 54: `thi` should be `the`
- on page 66: `The is based` should be `TDD is based`
- on page 67: `TDD process.` should be `TDD process`
- on page 106: `tests are specification` should be `tests are specifications`
- on page 106: `. When then deal` should be`, then we deal`
- on page 110: `in in` should be `in`
- on page 121: `the above two above folders` should be `the two folders above`
- on page 113: `accordingly Moreover` should be `accordingly. Moreover`
- on page 142: `repository, This` should be `repository. This`
- on page 232: `cannot access to the history` should be `cannot access the history`
- on page 296: `a Docker container running` should be `A Docker container running`
- on page 297: `print an hello message` should be `print a hello message`
- on page 303: `from the context into to the file system` should be `from the context into the file system`
- on page 303: `an optimal one` should be `the optimal one`
- on page 316: `the container we will enjoy` should be `the container will enjoy`
- on page 323: `n this chapter` should be `in this chapter`
- on page 325: `tutorial, We use` should be `tutorial, we use`
- on page 371: `an behavior` should be `a behavior`
- on page 391: `either by either` should be `either by`
- on page 392: `directly components of the application` should be `components of the application directly`
- on page 416: `such as a scenario` should be `such a scenario`
- on page 416: `has to be update` should be `has to be updated`
- on page 423: `Sonarqube` should be `SonarQube`
- on page 425: `and we land` should be `we land`
- on page 430: `ends with ruleKey` should be `ends with ruleKey.`
- on page 449: `. And` should be `and`

**Comment by LorenzoBettini** [comment]
WOW already 2 typos in the first pages O:)
Thanks for the feedback. :)
I'll fix them ASAP and leave the issue open in case other typos will be detected.
Then I'll release an updated version of the book.

**Comment by LorenzoBettini** [comment]
By the way "the the" can be found in many other places, I'll fix them all!

**Comment by miklossy** [comment]
@LorenzoBettini I am done here. You can fix the typos and close this issue after that.

**Comment by LorenzoBettini** [comment]
OK the new version has been published.
Thanks for your feedback! :)

**Comment by LorenzoBettini** [comment]
Oh no! I hadn't seen the further comments :'(
I'm reopening this and fix them really ASAP!

**Comment by LorenzoBettini** [comment]
I guess I'm not getting notifications when you simply edit a previous comment...

**Comment by LorenzoBettini** [comment]
Finally addressed all of them and published a new version of the book.
Just one remark:
`on page 66: "The is based" should be "TDD is based"`
I actually changed this into "and it is known as".

Thank you for your precious feedback!
Hope you enjoyed the book :)

**Comment by miklossy** [comment]
Yes, I found the book very enjoyable!
